Repository HSF/prmon, pull requests merged in 2020-06, with the labels that each got.

#117 Update plotting script to address #104
  package/scripts/prmon_plot.py
Labels: enhancement

#115 Plugin registry implementation
  .gitignore
  package/src/countmon.h
  package/src/cpumon.h
  package/src/iomon.h
  package/src/memmon.h
  package/src/netmon.h
  package/src/prmon.cpp
  package/src/registry.h
  package/src/wallmon.h
Labels: enhancement

#120 Check for variable consistency in the plotting script
  package/scripts/prmon_plot.py
Labels: enhancement

#116 Hardware information implementation
  README.md
  package/src/Imonitor.h
  package/src/countmon.cpp
  package/src/countmon.h
  package/src/cpumon.cpp
  package/src/cpumon.h
  package/src/iomon.cpp
  package/src/iomon.h
  package/src/memmon.cpp
  package/src/memmon.h
  package/src/netmon.cpp
  package/src/netmon.h
  package/src/prmon.cpp
  package/src/prmon.h
  package/src/wallmon.cpp
  package/src/wallmon.h
Labels: enhancement

#130 Putting in a basic GitHub Actions workflow
  .github/scripts/build-test.sh
  .github/workflows/ci.yml
  .travis.yml
  README.md
Labels: enhancement

#125 Add NVIDIA GPU monitoring
  CMakeLists.txt
  package/CMakeLists.txt
  package/src/Imonitor.h
  package/src/countmon.h
  package/src/cpumon.h
  package/src/iomon.h
  package/src/memmon.h
  package/src/netmon.h
  package/src/nvidiamon.cpp
  package/src/nvidiamon.h
  package/src/prmon.cpp
  package/src/utils.h
  package/src/wallmon.h
Labels: enhancement, question

#131 Adding a basic clang-format GitHub action
  .github/workflows/clang-format.yml
Labels: enhancement, question

#134 Omit running clang-format for pushes into master/stable
  .github/workflows/clang-format.yml
  package/src/cpumon.cpp
Labels: bug

#137 Arm fixes
  CMakeLists.txt
  package/src/cpumon.cpp
  package/src/prmon.cpp
  package/tests/burner.cpp
  package/tests/io-burner.cpp
  package/tests/mem-burner.cpp
Labels: work in progress

#139 Get the CPU information from lscpu
  package/src/cpumon.cpp
Labels: bug
